export const TRIGGER_TAKEEVERY_JOB = "TRIGGER_TAKEEVERY_JOB";
export const TRIGGER_TAKELATEST_JOB = "TRIGGER_TAKELATEST_JOB";
export const TRIGGER_TAKELEADING_JOB = "TRIGGER_TAKELAODING_JOB";
export const TRIGGER_THROTTLE_JOB = "TRIGGER_THROTTLE_JOB";
export const TRIGGER_TAKE_JOB = "TRIGGER_TAKE_JOB";
export const ADD_SAGA_TASK = "ADD_SAGA_TASK";
export const CLEAR_SAGA_TASK = "CLEAR_SAGA_TASK";
